"""Star reference catalog for API clients.

Descriptions adapted from J2TEAM vibe canchi (sao-data) where names match;
IDs and classifications come from the lasotuvi engine.
"""

from __future__ import annotations

from typing import Any

SAO_CATALOG: list[dict[str, Any]] = [
    {
        "id": 1,
        "ten": "Tử vi",
        "ngu_hanh": "O",
        "loai": 1,
        "phuong_vi": "Đế tinh",
        "am_duong": 1,
        "vong_trang_sinh": False,
        "mo_ta": "Đế tinh, chúa tể trung thiên. Sao đứng đầu trong hệ thống Tử Vi.",
        "y_nghia": "Quyền lực, lãnh đạo, cao quý, uy phong. Quý nhân phù trợ.",
    },
    {
        "id": 2,
        "ten": "Liêm trinh",
        "ngu_hanh": "H",
        "loai": 1,
        "phuong_vi": "Bắc đẩu tinh",
        "am_duong": 1,
        "vong_trang_sinh": False,
        "mo_ta": "Sao thứ phi, lưỡng diện. Vừa quý vừa sát.",
        "y_nghia": "Đa tài, sắc sảo, quyến rũ. Có tính hai mặt, cần cẩn trọng.",
    },
    {
        "id": 3,
        "ten": "Thiên đồng",
        "ngu_hanh": "T",
        "loai": 1,
        "phuong_vi": "Bắc đẩu tinh",
        "am_duong": 1,
        "vong_trang_sinh": False,
        "mo_ta": "Sao phúc tinh, chủ hưởng thụ, an nhàn.",
        "y_nghia": "Phúc lộc, an nhàn, hòa nhã. Đời sống thanh thản, ít lo lắng.",
    },
    {
        "id": 4,
        "ten": "Vũ khúc",
        "ngu_hanh": "K",
        "loai": 1,
        "phuong_vi": "Bắc đẩu tinh",
        "am_duong": -1,
        "vong_trang_sinh": False,
        "mo_ta": "Sao tài tinh, chủ về tài chính, võ nghệ.",
        "y_nghia": "Tài năng, quyết đoán, cương nghị. Giỏi kiếm tiền, quản lý tài chính.",
    },
    {
        "id": 5,
        "ten": "Thái Dương",
        "ngu_hanh": "H",
        "loai": 1,
        "phuong_vi": "Nam đẩu tinh",
        "am_duong": 1,
        "vong_trang_sinh": False,
        "mo_ta": "Sao Mặt trời, ánh sáng, quang minh.",
        "y_nghia": "Quang minh, chính trực, bác ái. Chủ về danh tiếng, sự nghiệp.",
    },
    {
        "id": 6,
        "ten": "Thiên cơ",
        "ngu_hanh": "M",
        "loai": 1,
        "phuong_vi": "Nam đẩu tinh",
        "am_duong": -1,
        "vong_trang_sinh": False,
        "mo_ta": "Sao trí tuệ, mưu lược, thiện biến.",
        "y_nghia": "Thông minh, linh hoạt, tài mưu lược. Giỏi tính toán, phân tích.",
    },
    {
        "id": 7,
        "ten": "Thiên phủ",
        "ngu_hanh": "O",
        "loai": 1,
        "phuong_vi": "Nam đẩu tinh",
        "am_duong": 1,
        "vong_trang_sinh": False,
        "mo_ta": "Sao kho lẫm, chủ kho tàng, của cải.",
        "y_nghia": "Giàu có, sung túc, ổn định. Giỏi tích trữ, quản lý tài sản.",
    },
    {
        "id": 8,
        "ten": "Thái âm",
        "ngu_hanh": "T",
        "loai": 1,
        "phuong_vi": "Bắc đẩu tinh",
        "am_duong": -1,
        "vong_trang_sinh": False,
        "mo_ta": "Sao Mặt trăng, chủ âm nhu, điền sản.",
        "y_nghia": "Thanh tú, nhu mì, chu đáo. Chủ về bất động sản, tài sản âm.",
    },
    {
        "id": 9,
        "ten": "Tham lang",
        "ngu_hanh": "T",
        "loai": 1,
        "phuong_vi": "Bắc đẩu tinh",
        "am_duong": -1,
        "vong_trang_sinh": False,
        "mo_ta": "Sao đào hoa, đa tài đa nghệ.",
        "y_nghia": "Tài hoa, giao tiếp tốt, ham muốn. Đa dạng tài năng nhưng dễ tham vọng.",
    },
    {
        "id": 10,
        "ten": "Cự môn",
        "ngu_hanh": "T",
        "loai": 1,
        "phuong_vi": "Bắc đẩu tinh",
        "am_duong": -1,
        "vong_trang_sinh": False,
        "mo_ta": "Sao ám tinh, chủ khẩu thiệt, thị phi.",
        "y_nghia": "Ăn nói, tranh biện, thị phi. Giỏi giao tiếp nhưng hay gây mâu thuẫn.",
    },
    {
        "id": 11,
        "ten": "Thiên tướng",
        "ngu_hanh": "T",
        "loai": 1,
        "phuong_vi": "Nam đẩu tinh",
        "am_duong": 1,
        "vong_trang_sinh": False,
        "mo_ta": "Sao ấn tinh, chủ chính trực, quý nhân.",
        "y_nghia": "Chính trực, phúc hậu, có quý nhân. Được người giúp đỡ.",
    },
    {
        "id": 12,
        "ten": "Thiên lương",
        "ngu_hanh": "M",
        "loai": 1,
        "phuong_vi": "Nam đẩu tinh",
        "am_duong": -1,
        "vong_trang_sinh": False,
        "mo_ta": "Sao ấm tinh, chủ bóng mát, che chở.",
        "y_nghia": "Nhân từ, che chở, phúc thọ. Hay giúp đỡ người khác.",
    },
    {
        "id": 13,
        "ten": "Thất sát",
        "ngu_hanh": "K",
        "loai": 1,
        "phuong_vi": "Nam đẩu tinh",
        "am_duong": 1,
        "vong_trang_sinh": False,
        "mo_ta": "Sao sát tinh, uy quyền, chiến đấu.",
        "y_nghia": "Uy quyền, quyết đoán, mạnh mẽ. Dám nghĩ dám làm, chịu áp lực.",
    },
    {
        "id": 14,
        "ten": "Phá quân",
        "ngu_hanh": "T",
        "loai": 1,
        "phuong_vi": "Bắc đẩu tinh",
        "am_duong": -1,
        "vong_trang_sinh": False,
        "mo_ta": "Sao hao tinh, phá cũ lập mới.",
        "y_nghia": "Đổi mới, phá cách, biến động. Hay thay đổi, cải cách mạnh mẽ.",
    },
    {
        "id": 15,
        "ten": "Thái tuế",
        "ngu_hanh": "H",
        "loai": 15,
        "phuong_vi": None,
        "am_duong": 0,
        "vong_trang_sinh": False,
        "mo_ta": "Sao tuế, kiện cáo.",
        "y_nghia": "Kiện tụng, thị phi, quan sự. Năm không thuận lợi.",
    },
    {
        "id": 16,
        "ten": "Thiếu dương",
        "ngu_hanh": "H",
        "loai": 5,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao dương nhỏ.",
        "y_nghia": "Sáng sủa, vui vẻ, may mắn.",
    },
    {
        "id": 17,
        "ten": "Tang môn",
        "ngu_hanh": "M",
        "loai": 12,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao tang, buồn thương.",
        "y_nghia": "Tang tóc, buồn phiền, mất mát người thân.",
    },
    {
        "id": 18,
        "ten": "Thiếu âm",
        "ngu_hanh": "T",
        "loai": 5,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao âm nhỏ.",
        "y_nghia": "Hiền lành, duyên dáng, phúc lộc.",
    },
    {
        "id": 19,
        "ten": "Quan phù",
        "ngu_hanh": "H",
        "loai": 12,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao quan tụng.",
        "y_nghia": "Kiện tụng, tranh chấp, quan sự.",
    },
    {
        "id": 20,
        "ten": "Tử phù",
        "ngu_hanh": "K",
        "loai": 12,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao bệnh tật.",
        "y_nghia": "Bệnh tật, ốm đau, sức khỏe kém.",
    },
    {
        "id": 21,
        "ten": "Tuế phá",
        "ngu_hanh": "H",
        "loai": 12,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao phá tuế.",
        "y_nghia": "Phá hoại, hao tổn, bất ổn.",
    },
    {
        "id": 22,
        "ten": "Long đức",
        "ngu_hanh": "T",
        "loai": 5,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao đức của rồng.",
        "y_nghia": "Nhân đức, phúc lộc, được kính trọng.",
    },
    {
        "id": 23,
        "ten": "Bạch hổ",
        "ngu_hanh": "K",
        "loai": 12,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao hung bạo, tai nạn.",
        "y_nghia": "Tai nạn, máu me, phẫu thuật. Nhưng cũng uy quyền.",
    },
    {
        "id": 24,
        "ten": "Phúc đức",
        "ngu_hanh": "O",
        "loai": 5,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao phúc đức.",
        "y_nghia": "Phúc đức dồi dào, may mắn.",
    },
    {
        "id": 25,
        "ten": "Điếu khách",
        "ngu_hanh": "H",
        "loai": 12,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao viếng tang.",
        "y_nghia": "Tang tóc, buồn thương, viếng tang.",
    },
    {
        "id": 26,
        "ten": "Trực phù",
        "ngu_hanh": "K",
        "loai": 16,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao trực, cứng rắn.",
        "y_nghia": "Cứng rắn, hay va chạm, tranh chấp.",
    },
    {
        "id": 27,
        "ten": "Lộc tồn",
        "ngu_hanh": "O",
        "loai": 3,
        "phuong_vi": "Bắc đẩu tinh",
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao tài lộc chính, giữ lộc.",
        "y_nghia": "Tài lộc bền vững, giữ tiền giỏi. Giàu có ổn định.",
    },
    {
        "id": 28,
        "ten": "Lực sĩ",
        "ngu_hanh": "H",
        "loai": 2,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao sức mạnh.",
        "y_nghia": "Sức mạnh, cường tráng, làm việc tốt.",
    },
    {
        "id": 29,
        "ten": "Thanh long",
        "ngu_hanh": "T",
        "loai": 5,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao rồng xanh, hỷ sự.",
        "y_nghia": "Vui mừng, may mắn, tài lộc.",
    },
    {
        "id": 30,
        "ten": "Tiểu hao",
        "ngu_hanh": "H",
        "loai": 12,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao hao tổn nhỏ.",
        "y_nghia": "Hao tổn nhỏ, chi tiêu vặt.",
    },
    {
        "id": 31,
        "ten": "Tướng quân",
        "ngu_hanh": "M",
        "loai": 4,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao tướng, chỉ huy.",
        "y_nghia": "Uy quyền, lãnh đạo, nhưng cũng cương ngạnh.",
    },
    {
        "id": 32,
        "ten": "Tấu thư",
        "ngu_hanh": "K",
        "loai": 3,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao tấu sớ, giấy tờ.",
        "y_nghia": "Văn bản, giấy tờ thuận lợi, thi đỗ.",
    },
    {
        "id": 33,
        "ten": "Phi liêm",
        "ngu_hanh": "H",
        "loai": 2,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao bay nhanh.",
        "y_nghia": "Biến động nhanh, bất ổn, tai bay vạ gió.",
    },
    {
        "id": 34,
        "ten": "Hỷ thần",
        "ngu_hanh": "H",
        "loai": 5,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao thần vui.",
        "y_nghia": "Vui vẻ, hạnh phúc, gặp niềm vui.",
    },
    {
        "id": 35,
        "ten": "Bệnh phù",
        "ngu_hanh": "O",
        "loai": 12,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao bệnh.",
        "y_nghia": "Bệnh tật, ốm đau.",
    },
    {
        "id": 36,
        "ten": "Đại hao",
        "ngu_hanh": "H",
        "loai": 12,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao hao tổn lớn.",
        "y_nghia": "Hao tổn tài chính lớn, chi tiêu nhiều.",
    },
    {
        "id": 37,
        "ten": "Phục binh",
        "ngu_hanh": "H",
        "loai": 13,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao phục kích.",
        "y_nghia": "Bị phục kích, âm mưu, tiểu nhân.",
    },
    {
        "id": 38,
        "ten": "Quan phù",
        "ngu_hanh": "H",
        "loai": 12,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao quan tụng.",
        "y_nghia": "Kiện tụng, tranh chấp, quan sự.",
    },
    {
        "id": 39,
        "ten": "Tràng sinh",
        "ngu_hanh": "T",
        "loai": 5,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": True,
        "mo_ta": None,
        "y_nghia": None,
    },
    {
        "id": 40,
        "ten": "Mộc dục",
        "ngu_hanh": "T",
        "loai": 14,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": True,
        "mo_ta": None,
        "y_nghia": None,
    },
    {
        "id": 41,
        "ten": "Quan đới",
        "ngu_hanh": "K",
        "loai": 4,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": True,
        "mo_ta": None,
        "y_nghia": None,
    },
    {
        "id": 42,
        "ten": "Lâm quan",
        "ngu_hanh": "K",
        "loai": 7,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": True,
        "mo_ta": None,
        "y_nghia": None,
    },
    {
        "id": 43,
        "ten": "Đế vượng",
        "ngu_hanh": "K",
        "loai": 5,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": True,
        "mo_ta": None,
        "y_nghia": None,
    },
    {
        "id": 44,
        "ten": "Suy",
        "ngu_hanh": "T",
        "loai": 12,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": True,
        "mo_ta": None,
        "y_nghia": None,
    },
    {
        "id": 45,
        "ten": "Bệnh",
        "ngu_hanh": "H",
        "loai": 12,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": True,
        "mo_ta": None,
        "y_nghia": None,
    },
    {
        "id": 46,
        "ten": "Tử",
        "ngu_hanh": "H",
        "loai": 12,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": True,
        "mo_ta": None,
        "y_nghia": None,
    },
    {
        "id": 47,
        "ten": "Mộ",
        "ngu_hanh": "O",
        "loai": 2,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": True,
        "mo_ta": None,
        "y_nghia": None,
    },
    {
        "id": 48,
        "ten": "Tuyệt",
        "ngu_hanh": "O",
        "loai": 12,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": True,
        "mo_ta": None,
        "y_nghia": None,
    },
    {
        "id": 49,
        "ten": "Thai",
        "ngu_hanh": "O",
        "loai": 14,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": True,
        "mo_ta": None,
        "y_nghia": None,
    },
    {
        "id": 50,
        "ten": "Dưỡng",
        "ngu_hanh": "M",
        "loai": 2,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": True,
        "mo_ta": None,
        "y_nghia": None,
    },
    {
        "id": 51,
        "ten": "Đà la",
        "ngu_hanh": "K",
        "loai": 11,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao sát tinh, kéo lùi, cản trở.",
        "y_nghia": "Chậm trễ, cản trở, lề mề. Nhưng cũng chính xác, cẩn thận.",
    },
    {
        "id": 52,
        "ten": "Kình dương",
        "ngu_hanh": "K",
        "loai": 11,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao sát tinh, cương cường.",
        "y_nghia": "Cương quyết, bướng bỉnh, dễ va chạm. Có thể gây tai nạn, tranh chấp.",
    },
    {
        "id": 53,
        "ten": "Địa không",
        "ngu_hanh": "H",
        "loai": 11,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Không vong tinh, trống rỗng.",
        "y_nghia": "Mất mát, hao tổn, không có gì. Nhưng cũng sáng tạo, triết học.",
    },
    {
        "id": 54,
        "ten": "Địa kiếp",
        "ngu_hanh": "H",
        "loai": 11,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Kiếp nạn tinh, tai họa.",
        "y_nghia": "Tai nạn, kiếp nạn, mất mát bất ngờ. Biến động mạnh.",
    },
    {
        "id": 55,
        "ten": "Linh tinh",
        "ngu_hanh": "H",
        "loai": 11,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao sát tinh, âm ỉ, kéo dài.",
        "y_nghia": "Lo lắng, âu sầu, tai họa âm thầm. Bền bỉ nhưng dễ lo âu.",
    },
    {
        "id": 56,
        "ten": "Hỏa tinh",
        "ngu_hanh": "H",
        "loai": 11,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao sát tinh, nóng nảy, bùng phát.",
        "y_nghia": "Nóng nảy, bốc đồng, tai họa bất ngờ. Nhưng cũng mạnh mẽ, quyết liệt.",
    },
    {
        "id": 57,
        "ten": "Văn xương",
        "ngu_hanh": "K",
        "loai": 6,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao văn chương, học vấn.",
        "y_nghia": "Thông minh, học giỏi, có tài văn chương, thi cử đỗ đạt.",
    },
    {
        "id": 58,
        "ten": "Văn Khúc",
        "ngu_hanh": "T",
        "loai": 6,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao nghệ thuật, tài hoa.",
        "y_nghia": "Tài hoa, nghệ thuật, khéo léo, giỏi giao tiếp.",
    },
    {
        "id": 59,
        "ten": "Thiên khôi",
        "ngu_hanh": "H",
        "loai": 6,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Quý nhân dương, sao dẫn đường.",
        "y_nghia": "Gặp quý nhân giúp đỡ, may mắn, thuận lợi trong sự nghiệp.",
    },
    {
        "id": 60,
        "ten": "Thiên việt",
        "ngu_hanh": "H",
        "loai": 6,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Quý nhân âm, sao hỗ trợ.",
        "y_nghia": "Được quý nhân âm thầm giúp đỡ, gặp may trong nguy.",
    },
    {
        "id": 61,
        "ten": "Tả phù",
        "ngu_hanh": "O",
        "loai": 2,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Trợ tinh bên trái, phù trợ chúa tinh.",
        "y_nghia": "Quý nhân phù trợ, nhiều bạn bè, được giúp đỡ.",
    },
    {
        "id": 62,
        "ten": "Hữu bật",
        "ngu_hanh": "O",
        "loai": 2,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Trợ tinh bên phải, phù trợ chúa tinh.",
        "y_nghia": "Quý nhân phù trợ, được bề trên nâng đỡ.",
    },
    {
        "id": 63,
        "ten": "Long trì",
        "ngu_hanh": "T",
        "loai": 3,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao rồng, quý tộc.",
        "y_nghia": "Cao quý, được quý nhân giúp, tài lộc.",
    },
    {
        "id": 64,
        "ten": "Phượng các",
        "ngu_hanh": "O",
        "loai": 3,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao phượng, vinh hoa.",
        "y_nghia": "Vinh hoa, phú quý, danh vọng cao.",
    },
    {
        "id": 65,
        "ten": "Tam thai",
        "ngu_hanh": "M",
        "loai": 7,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao tam tài.",
        "y_nghia": "Văn chương, thi đỗ, học vấn cao.",
    },
    {
        "id": 66,
        "ten": "Bát tọa",
        "ngu_hanh": "T",
        "loai": 7,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao bát vị.",
        "y_nghia": "Văn chương, chức vụ, học hành giỏi.",
    },
    {
        "id": 67,
        "ten": "Ân quang",
        "ngu_hanh": "M",
        "loai": 3,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao ân huệ, sáng suốt.",
        "y_nghia": "Ân huệ, phúc phận, được giúp đỡ.",
    },
    {
        "id": 68,
        "ten": "Thiên quý",
        "ngu_hanh": "O",
        "loai": 3,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao quý nhân trời.",
        "y_nghia": "Quý nhân, may mắn, cao sang.",
    },
    {
        "id": 69,
        "ten": "Thiên khốc",
        "ngu_hanh": "T",
        "loai": 12,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao khóc.",
        "y_nghia": "Buồn thương, khóc lóc, tang tóc.",
    },
    {
        "id": 70,
        "ten": "Thiên hư",
        "ngu_hanh": "T",
        "loai": 12,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao trống rỗng.",
        "y_nghia": "Hao hụt, trống rỗng, mất mát.",
    },
    {
        "id": 71,
        "ten": "Thiên đức",
        "ngu_hanh": "H",
        "loai": 5,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao phúc đức trời cho.",
        "y_nghia": "Phúc đức, may mắn, được trời phù hộ.",
    },
    {
        "id": 72,
        "ten": "Nguyệt đức",
        "ngu_hanh": "H",
        "loai": 5,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao phúc đức mẹ.",
        "y_nghia": "Phúc từ mẹ, may mắn, duyên lành.",
    },
    {
        "id": 73,
        "ten": "Thiên hình",
        "ngu_hanh": "H",
        "loai": 15,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao hình phạt, kỷ luật.",
        "y_nghia": "Kỷ luật, nghiêm khắc, hình phạt. Hợp với ngành luật, công an.",
    },
    {
        "id": 74,
        "ten": "Thiên riêu",
        "ngu_hanh": "T",
        "loai": 13,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": None,
        "y_nghia": None,
    },
    {
        "id": 75,
        "ten": "Thiên y",
        "ngu_hanh": "T",
        "loai": 5,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao y dược, chữa bệnh.",
        "y_nghia": "Giỏi y dược, chữa bệnh, sức khỏe tốt.",
    },
    {
        "id": 76,
        "ten": "Quốc ấn",
        "ngu_hanh": "O",
        "loai": 6,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao ấn triện, quyền chức.",
        "y_nghia": "Có chức vụ, được phong tước, quyền hành chính thức.",
    },
    {
        "id": 77,
        "ten": "Đường phù",
        "ngu_hanh": "M",
        "loai": 4,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao quyền thế, quan chức.",
        "y_nghia": "Có quyền thế, được bổ nhiệm, thăng chức.",
    },
    {
        "id": 78,
        "ten": "Đào hoa",
        "ngu_hanh": "M",
        "loai": 8,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao đào hoa, sắc đẹp, duyên dáng.",
        "y_nghia": "Duyên dáng, quyến rũ, giao tiếp tốt. Nghệ thuật, giải trí.",
    },
    {
        "id": 79,
        "ten": "Hồng loan",
        "ngu_hanh": "T",
        "loai": 8,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao đào hoa chính, hôn nhân.",
        "y_nghia": "Duyên số, hôn nhân, tình cảm thuận lợi. Sắc đẹp, duyên dáng.",
    },
    {
        "id": 80,
        "ten": "Thiên hỷ",
        "ngu_hanh": "T",
        "loai": 5,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao vui mừng, hỷ tín.",
        "y_nghia": "Tin vui, hỷ sự, may mắn. Có thể báo hiệu đám cưới, sinh con.",
    },
    {
        "id": 81,
        "ten": "Thiên giải",
        "ngu_hanh": "H",
        "loai": 5,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao giải nạn trời.",
        "y_nghia": "Giải trừ tai họa, may mắn thoát nạn.",
    },
    {
        "id": 82,
        "ten": "Địa giải",
        "ngu_hanh": "O",
        "loai": 5,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao giải nạn đất.",
        "y_nghia": "Giải trừ tai họa, bình an.",
    },
    {
        "id": 83,
        "ten": "Giải thần",
        "ngu_hanh": "M",
        "loai": 5,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao giải nạn.",
        "y_nghia": "Giải trừ hung xấu, hóa giải tai nạn.",
    },
    {
        "id": 84,
        "ten": "Thai phụ",
        "ngu_hanh": "K",
        "loai": 6,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao phụ tá, hỗ trợ.",
        "y_nghia": "Được hỗ trợ, giúp đỡ trong học vấn và sự nghiệp.",
    },
    {
        "id": 85,
        "ten": "Phong cáo",
        "ngu_hanh": "O",
        "loai": 4,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao sắc phong, vinh hiển.",
        "y_nghia": "Được phong thưởng, khen ngợi, danh hiệu.",
    },
    {
        "id": 86,
        "ten": "Thiên tài",
        "ngu_hanh": "O",
        "loai": 2,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao tài năng thiên bẩm.",
        "y_nghia": "Tài năng bẩm sinh, khéo léo, sáng tạo.",
    },
    {
        "id": 87,
        "ten": "Thiên thọ",
        "ngu_hanh": "O",
        "loai": 5,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao trường thọ.",
        "y_nghia": "Sống lâu, sức khỏe tốt, phúc thọ.",
    },
    {
        "id": 88,
        "ten": "Thiên thương",
        "ngu_hanh": "O",
        "loai": 12,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao thương tích.",
        "y_nghia": "Thương tích, tai nạn, đau đớn.",
    },
    {
        "id": 89,
        "ten": "Thiên sứ",
        "ngu_hanh": "T",
        "loai": 12,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao sứ giả.",
        "y_nghia": "Tin tức, thông báo, nhưng cũng bệnh tật.",
    },
    {
        "id": 90,
        "ten": "Thiên la",
        "ngu_hanh": "O",
        "loai": 12,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Lưới trời, ràng buộc trên.",
        "y_nghia": "Bị ràng buộc, khó thoát, trở ngại từ trên.",
    },
    {
        "id": 91,
        "ten": "Địa võng",
        "ngu_hanh": "O",
        "loai": 12,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Lưới đất, ràng buộc dưới.",
        "y_nghia": "Bị ràng buộc, khó thoát, trở ngại từ dưới.",
    },
    {
        "id": 92,
        "ten": "Hóa khoa",
        "ngu_hanh": "T",
        "loai": 5,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Tứ hóa: Khoa. Danh tiếng, học vấn.",
        "y_nghia": "Danh tiếng, học vấn, thi đỗ, được nể trọng.",
    },
    {
        "id": 93,
        "ten": "Hóa quyền",
        "ngu_hanh": "T",
        "loai": 4,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Tứ hóa: Quyền. Quyền lực, làm chủ.",
        "y_nghia": "Quyền lực, uy tín, khả năng lãnh đạo, kiểm soát.",
    },
    {
        "id": 94,
        "ten": "Hóa lộc",
        "ngu_hanh": "M",
        "loai": 3,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Tứ hóa: Lộc. Tài lộc, may mắn.",
        "y_nghia": "Tài lộc dồi dào, cơ hội kiếm tiền, sự nghiệp thuận lợi.",
    },
    {
        "id": 95,
        "ten": "Hóa kỵ",
        "ngu_hanh": "T",
        "loai": 13,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Tứ hóa: Kỵ. Trở ngại, thị phi.",
        "y_nghia": "Trở ngại, phiền não, thị phi, tranh chấp. Cần cẩn trọng.",
    },
    {
        "id": 96,
        "ten": "Cô thần",
        "ngu_hanh": "O",
        "loai": 13,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao cô đơn dương, lẻ loi.",
        "y_nghia": "Cô đơn, lẻ loi, thiếu bạn đời. Nhưng cũng độc lập, tự chủ.",
    },
    {
        "id": 97,
        "ten": "Quả tú",
        "ngu_hanh": "O",
        "loai": 13,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao cô đơn âm, góa bụa.",
        "y_nghia": "Cô quạnh, thiếu bạn đời. Nhưng cũng thanh cao, tự lập.",
    },
    {
        "id": 98,
        "ten": "Thiên mã",
        "ngu_hanh": "H",
        "loai": 3,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao di chuyển, vận động.",
        "y_nghia": "Di chuyển nhiều, năng động, thay đổi. Hợp kinh doanh, xuất ngoại.",
    },
    {
        "id": 99,
        "ten": "Phá toái",
        "ngu_hanh": "H",
        "loai": 12,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao phá hoại nhỏ.",
        "y_nghia": "Phá hoại, hao tổn nhỏ, bất ổn.",
    },
    {
        "id": 100,
        "ten": "Thiên quan",
        "ngu_hanh": "H",
        "loai": 5,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao quan chức.",
        "y_nghia": "Có chức vụ, quyền hành, sự nghiệp hanh thông.",
    },
    {
        "id": 101,
        "ten": "Thiên phúc",
        "ngu_hanh": "H",
        "loai": 5,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao phúc trời.",
        "y_nghia": "Phúc lộc, may mắn, trời cho phúc.",
    },
    {
        "id": 102,
        "ten": "Lưu hà",
        "ngu_hanh": "T",
        "loai": 12,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao tai nạn nước.",
        "y_nghia": "Tai nạn liên quan nước, đuối nước.",
    },
    {
        "id": 103,
        "ten": "Thiên trù",
        "ngu_hanh": "O",
        "loai": 5,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao bếp trời, ẩm thực.",
        "y_nghia": "Ẩm thực, no đủ, phúc lộc ăn uống.",
    },
    {
        "id": 104,
        "ten": "Kiếp sát",
        "ngu_hanh": "H",
        "loai": 11,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao kiếp nạn, cướp bóc.",
        "y_nghia": "Kiếp nạn, bị cướp, tai họa bất ngờ.",
    },
    {
        "id": 105,
        "ten": "Hoa cái",
        "ngu_hanh": "K",
        "loai": 14,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao nghệ thuật, thanh cao.",
        "y_nghia": "Nghệ thuật, thanh cao, tôn giáo. Có phong cách riêng.",
    },
    {
        "id": 106,
        "ten": "Văn tinh",
        "ngu_hanh": "H",
        "loai": 6,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": None,
        "y_nghia": None,
    },
    {
        "id": 107,
        "ten": "Đẩu quân",
        "ngu_hanh": "H",
        "loai": 5,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao quân đấu.",
        "y_nghia": "Tranh đấu, cạnh tranh, áp lực.",
    },
    {
        "id": 108,
        "ten": "Thiên không",
        "ngu_hanh": "T",
        "loai": 11,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": "Sao không vong, trống rỗng trên trời.",
        "y_nghia": "Không thực tế, ảo tưởng. Nhưng giỏi sáng tạo, triết học, tôn giáo.",
    },
    {
        "id": 109,
        "ten": "Bác sỹ",
        "ngu_hanh": "T",
        "loai": 5,
        "phuong_vi": None,
        "am_duong": None,
        "vong_trang_sinh": False,
        "mo_ta": None,
        "y_nghia": None,
    },
]

_BY_ID = {s["id"]: s for s in SAO_CATALOG}
_BY_TEN = {s["ten"].casefold(): s for s in SAO_CATALOG}


def get_sao_by_id(sao_id: int) -> dict[str, Any] | None:
    return _BY_ID.get(sao_id)


def get_sao_by_ten(ten: str) -> dict[str, Any] | None:
    return _BY_TEN.get(ten.casefold())
